services:
  app:
    ports: []
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - SANCTUM_STATEFUL_DOMAINS=localhost,localhost:8000,localhost:5173
    volumes:
      - .:/app
      - ./.docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    command: php-fpm
    networks:
      - default

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/app
      - ./nginx.local.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - default

  node:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    command: sh -lc "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    depends_on:
      - app
    networks:
      - default
