services:
  app: &base
    build:
      context: ./.docker
      dockerfile: Dockerfile
    command: ["composer", "run", "dev"]
    working_dir: /app
    volumes:
      - .:/app
      - ./.docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "8000:8000"
      - "5173:5173"
    environment:
      - APP_ENV=dev
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
    depends_on:
      db:
        condition: service_healthy


  migrations:
    <<: *base
    command: ["php", "artisan", "migrate"]

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  db_data:
    driver: local

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.33.0.0/16
