services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    working_dir: /app
    expose:
      - "9000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://www.oficialfloov.com.br
      - APP_TIMEZONE=America/Sao_Paulo
      - TRUSTED_PROXIES=*
    depends_on:
      db:
        condition: service_healthy
    networks:
      - proxy-tier
      - default
    restart: unless-stopped
    volumes:
      - public-build:/app/public
      - ./storage/app/public:/app/storage/app/public

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.local.prod.conf:/etc/nginx/conf.d/default.conf
      - public-build:/app/public
      - ./storage/app/public:/app/storage/app/public
    expose:
      - "80"
    depends_on:
      - app
    environment:
      - VIRTUAL_HOST=www.oficialfloov.com.br
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=www.oficialfloov.com.br
      - LETSENCRYPT_EMAIL=oficialfloov@gmail.com
    networks:
      - proxy-tier
      - default
    restart: unless-stopped


  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: floov
      MYSQL_USER: floov
      MYSQL_PASSWORD: floov
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    profiles: ["prod"]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - proxy-tier
    restart: unless-stopped

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-letsencrypt
    profiles: ["prod"]
    depends_on:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=oficialfloov@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - proxy-tier
    restart: unless-stopped

volumes:
  db_data:
  public-build:

networks:
  proxy-tier:
    external: false
  default:
    driver: bridge
